server:
  port: 80  #tomcat端口号
  servlet:
    context-path: / #项目根路径/应用上下文路径

#druid连接池配置
spring:
  datasource:
    # jdbc配置
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    ##password: 123456
    password: root
    url: jdbc:mysql://47.104.107.11:3306/book_store?useUnicode=true&characterEncoding&useSSL=false&serverTimezone=UTC
    # 指定数据库连接池类型，不指定则默认使用hikari
    type: com.alibaba.druid.pool.DruidDataSource
    # druid连接池配置
    initialSize: 1  #初始化大小
    maxActive: 20 #最大连接数
    minIdle: 1  #最小连接数
    maxWait: 60000  #获取连接等待超时的时间
    testOnBorrow: true  #连接时是否检查连接可用性
    testOnReturn: false #归还连接时是否检查连接可用性
  servlet:
    #文件解析器
    multipart:
      enabled: true
      #设置单个文件的上传大小
      max-file-size: 200MB
      #设置总上传文件大小
      max-request-size: 1000MB

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true

#静态模板引擎
thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    content-type: text/html


